on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.5"  # Found on Ubuntu 16.04
          - "3.8"  # Found on Ubuntu 18.04 / 20.04
          - "3.10" # Found on Ubuntu 22.04
          - "3.12" # Found on Ubuntu 24.04
    container:
      image: python:${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Git inside test environment
        run: |
          git config --global user.name test
          git config --global user.email test
      - name: Install cram
        run: pip install cram
      - name: Run unit tests
        run: python3 -m unittest discover -v
      - name: Run integration tests
        run: cram tests
